# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuaris', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delicte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haGuanyatelBe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Districte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='denuncia',
            name='districte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delictes.Districte'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='supervillano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supers.Supervillano'),
        ),
        migrations.AddField(
            model_name='delicte',
            name='denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delictes.Denuncia'),
        ),
        migrations.AddField(
            model_name='delicte',
            name='policia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuaris.Perfil'),
        ),
        migrations.AddField(
            model_name='delicte',
            name='superheroi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supers.Superheroi'),
        ),
    ]
