# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_auto_20170508_1344'),
        ('supers', '0002_auto_20170508_1344'),
        ('delictes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delicte',
            name='denuncia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='delictes.Denuncia'),
        ),
        migrations.AddField(
            model_name='delicte',
            name='policia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuaris.Perfil'),
        ),
        migrations.AddField(
            model_name='delicte',
            name='superheroi',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supers.Superheroi'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='supervillano',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supers.Supervillano'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
