# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delictes', '0002_auto_20170505_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
