# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delictes', '0002_auto_20170508_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districte',
            name='nom',
            field=models.CharField(choices=[('D1-NORD GOTHAM', 'D1-Nord Gotham'), ('D2-GOTHAM CENTRE', 'D2-Gotham Centre'), ('D3-ARKHAM CITY', 'D3-Arkham City'), ('D4-GOTHAM EAST', 'D4-Gotham East '), ('D5-GOTHAM SUD', 'D5-Gotham Sud'), ('D6-BRONX GOTHAM', 'D6-Bronx GOTHAM')], max_length=200),
        ),
    ]
