# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delictes', '0003_auto_20170513_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districte',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
