# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delictes', '0005_auto_20170515_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delicte',
            name='denuncia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delictes.Denuncia'),
        ),
    ]
