# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_policia', models.BooleanField(default=False)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_ciutada', models.BooleanField(default=False)),
                ('es_superheroi', models.BooleanField(default=False)),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
