# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciutada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Policia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_placa', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='es_admin',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='es_ciutada',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='es_policia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='es_superheroi',
        ),
        migrations.AddField(
            model_name='policia',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuaris.Perfil'),
        ),
        migrations.AddField(
            model_name='ciutada',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuaris.Perfil'),
        ),
    ]
