# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_auto_20170506_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superheroi',
            name='user',
        ),
        migrations.RenameField(
            model_name='ciutada',
            old_name='user',
            new_name='usuari',
        ),
        migrations.RenameField(
            model_name='policia',
            old_name='user',
            new_name='usuari',
        ),
        migrations.DeleteModel(
            name='Superheroi',
        ),
    ]
