# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_auto_20170508_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='usuari',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
