# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0003_auto_20170511_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='policia',
            name='es_superpolicia',
            field=models.BooleanField(default=False),
        ),
    ]
