# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superheroi',
            fields=[
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('superpoder', models.CharField(max_length=100, verbose_name='Superpoder')),
                ('power', models.PositiveIntegerField(verbose_name='Powergeneration')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('heroi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disponibilitat', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supervillano',
            fields=[
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('superpoder', models.CharField(max_length=100, verbose_name='Superpoder')),
                ('power', models.PositiveIntegerField(verbose_name='Powergeneration')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('villano_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
