# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delictes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superheroi',
            fields=[
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('superpoder', models.CharField(max_length=100, verbose_name='Superpoder')),
                ('power', models.PositiveIntegerField(verbose_name='Powergeneration')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('heroi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disponibilitat', models.DateTimeField()),
                ('districte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delictes.Districte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supervillano',
            fields=[
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('superpoder', models.CharField(max_length=100, verbose_name='Superpoder')),
                ('power', models.PositiveIntegerField(verbose_name='Powergeneration')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('villano_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aparensa', models.CharField(max_length=200)),
                ('graumaldat', models.CharField(max_length=50, verbose_name='Grau de Maldat')),
                ('districte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delictes.Districte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
