# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroi',
            name='usuari',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervillano',
            name='aparensa',
            field=models.CharField(max_length=200, verbose_name='Aparen\xe7a'),
        ),
    ]
