# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_auto_20170508_1344'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroi',
            name='perfil',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='usuaris.Perfil'),
        ),
        migrations.AlterField(
            model_name='supervillano',
            name='aparensa',
            field=models.CharField(max_length=200, verbose_name='Aparen\xe7a'),
        ),
    ]
