# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_auto_20170508_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superheroi',
            name='position',
        ),
        migrations.RemoveField(
            model_name='supervillano',
            name='position',
        ),
    ]
